### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Xeiv** [ful1e5/bibata#35]
Hello, I can't download the cursor and all the images are just endlessly loading.

**Comment by ful1e5** [comment]
@Xeiv Refreshed Redis cache. Hopefully, this fixes the issue. Related to #31.

**Comment by a-usr** [comment]
Im still getting 232 or less 403's from aws

**Comment by k14lb3** [comment]
Same issue.

**Comment by ful1e5** [comment]
`403` is an authentication error. It's generated when accessing Figma's S3 files. I re-generated the _Figma Access Token_ and refreshed Bibata's Redis caches several times, but the same issue persists.

I suspect this might be due to recent major updates in Figma, although there haven't been any changes at the API level as noted in their [API changelogs](https://www.figma.com/developers/api#changelog). It could also be an issue with the Figma API Node.js library, or it might be a problem with Figma itself.

Currently, I'm investigating the issue. I'll keep updating on this issue here.

![image](https://github.com/user-attachments/assets/50f9020f-3b8b-4cb7-858d-05e963db6474)

## Errors Inspection
![image](https://github.com/user-attachments/assets/6c308e43-4b54-41de-8f89-1c0cbe7ba5e5)
![image](https://github.com/user-attachments/assets/1276d01a-ae16-437d-aa26-0c451e83413f)

**Comment by ful1e5** [comment]
Fixed with a337f9565e90c01e69caa0cf340f98153f0f40c3.

**Comment by izmyname** [comment]
I know it's closed, but I faced the same problem right now. Can't render the images
